{
 "title": "Erigon Gnosis Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "tx_pool_counters",
    "label": "TxPoolCounters",
    "query": "{job=\"geth\"}"
   },
   { "name": "job", "query": "geth" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   { "name": "instance", "label": "instance", "query": "db_get" }
  ]
 },
 "panels": [
  { "title": "Stages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Execution (stage 4)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "chain_execution{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "execution: {{quantile}},  {{instance}}"
    }
   ]
  },
  {
   "title": "Merkle Root calculation (stage 5)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "trie_subtrieloader_flatdb{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "trie_subtrieloader_flatdb: {{quantile}}, {{instance}}"
    },
    {
     "expr": "trie_subtrieloader_witnessdb{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "trie_subtrieloader_witnessdb: {{quantile}}, {{instance}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Commit event marker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(db_commit_big_batch_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "get/sec: {{instance}}"
    }
   ]
  },
  {
   "title": "Get",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "db_get{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "db_get: {{quantile}}, {{instance}}"
    },
    {
     "expr": "db_put{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "db_put: {{quantile}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Get calls/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_get_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "get/sec: {{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_sysload{instance=~\"$instance\"}",
     "legendFormat": "system: {{instance}}"
    },
    {
     "expr": "system_cpu_syswait{instance=~\"$instance\"}",
     "legendFormat": "iowait: {{instance}}"
    },
    {
     "expr": "system_cpu_procload{instance=\"$instance\"}",
     "legendFormat": "geth"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(system_memory_allocs{instance=~\"$instance\"}[10m])",
     "legendFormat": "alloc per 10min: {{instance}}"
    },
    {
     "expr": "system_memory_used{instance=~\"$instance\"}",
     "legendFormat": "used: {{instance}}"
    },
    {
     "expr": "system_memory_held{instance=\"$instance\"}",
     "legendFormat": "held"
    }
   ]
  },
  {
   "title": "GC Stop the World",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(system_memory_pauses{instance=~\"$instance\"}[1m])",
     "legendFormat": "system/memory/pauses: {{instance}}"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go/goroutines: {{instance}}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go/threads: {{instance}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{instance=~\"$instance\"}[1m])",
     "legendFormat": "read: {{instance}}"
    },
    {
     "expr": "rate(system_disk_writebytes{instance=~\"$instance\"}[1m])",
     "legendFormat": "write: {{instance}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\"}[1m])",
     "legendFormat": "ingress: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
     "legendFormat": "dials: {{instance}}"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
     "legendFormat": "serves: {{instance}}"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "chain_head_header{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "chain_head_block{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chain_head_header{instance=~\"$instance\"}",
     "legendFormat": "header: {{instance}}"
    },
    {
     "expr": "chain_head_receipt{instance=~\"$instance\"}",
     "legendFormat": "receipt: {{instance}}"
    },
    {
     "expr": "chain_head_block{instance=~\"$instance\"}",
     "legendFormat": "block: {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "executable: {{instance}}"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "gapped: {{instance}}"
    },
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "local: {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=~\"$instance\"}[1m])",
     "legendFormat": "valid: {{instance}}"
    },
    {
     "expr": "rate(txpool_invalid{instance=~\"$instance\"}[1m])",
     "legendFormat": "invalid: {{instance}}"
    },
    {
     "expr": "rate(txpool_underpriced{instance=\"$instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  { "title": "Trie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Trie Load Amounts (per 10min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(trie_subtrieloader_flatdb_count{instance=~\"$instance\"}[10m:30s])",
     "legendFormat": "trie_resolve_stateful_count: {{instance}}"
    },
    {
     "expr": "increase(trie_subtrieloader_witnessdb_count{instance=~\"$instance\"}[10m:30s])",
     "legendFormat": "trie_resolve_stateless_count: {{instance}}"
    }
   ]
  },
  {
   "title": "Private api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true
  },
  {
   "title": "gRPC call, error rates ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_started_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Calls: {{grpc_service}}.{{grpc_method}}, {{instance}}"
    },
    {
     "expr": "sum by (grpc_service, grpc_method, instance) (rate(grpc_server_handled_total{instance=~\"$instance\",grpc_code!=\"OK\"}[1m])) ",
     "legendFormat": "Errors: {{grpc_service}}.{{grpc_method}}, {{instance}}"
    }
   ]
  }
 ]
}